### ISSUE TITLE
Netdiscover on DO

### ISSUE THREAD

**Issue by juansalvatella** [CyCoreSystems/netdiscover#2]
Hi Sean,

I've recently deployed a K8s cluster in DO with Kamailio, Asterisk and asterisk-config. Almost everything seems to run as expected but there seems to be an issue with netdiscover. Calls are not getting through Kamailio to Asterisk because the proxies.conf generated by asterisk-config is picking up the public IP and not the private one.

I ran netdiscover inside Kamailio and the IPs returned are both the public one:
![image](https://user-images.githubusercontent.com/4377347/87174725-e8efac80-c2d7-11ea-992d-80e9bfbfcd0c.png)

Any hints on what could be the issue?

**Comment by juansalvatella** [comment]
Checking out the implementation it seems that [it has been left out](https://github.com/CyCoreSystems/netdiscover/blob/master/discover/digitalocean.go) on purpose. I ran a curl inside the container to check if the IP is properly returned and it does:

![image](https://user-images.githubusercontent.com/4377347/87176228-1b9aa480-c2da-11ea-9736-61effc1a8c09.png)

Thanks!

**Comment by Ulexus** [comment]
Ah, interesting.  In my testing, it always returned empty for me.  I'm happy to uncomment that, if it works for you.
